[Model]
dir = "climatearchive_sample_data/data"
name = "Bridge"
resolutions = [[3.75, -9.0]]
[Model.Atmosphere]
levels = [1000, 850, 700, 500, 200, 100, 10]
unit = "hPa"
[Model.Ocean]
levels = [0, 100, 200, 500, 1000, 2000, 4000]
unit = "m"

[clt]
preprocessing = "BRIDGE"
processing = "BRIDGE"
[[clt.variables]]
files=[
    "{id}/climate/{id}a.pdcljan.nc",
    "{id}/climate/{id}a.pdclfeb.nc",
    "{id}/climate/{id}a.pdclmar.nc",
    "{id}/climate/{id}a.pdclapr.nc",
    "{id}/climate/{id}a.pdclmay.nc",
    "{id}/climate/{id}a.pdcljun.nc",
    "{id}/climate/{id}a.pdcljul.nc",
    "{id}/climate/{id}a.pdclaug.nc",
    "{id}/climate/{id}a.pdclsep.nc",
    "{id}/climate/{id}a.pdcloct.nc",
    "{id}/climate/{id}a.pdclnov.nc",
    "{id}/climate/{id}a.pdcldec.nc",
]
variable = "totCloud_mm_ua"

[tas]
preprocessing = "BRIDGE"
processing = "BRIDGE"
[[tas.variables]]
files=[
    "{id}/climate/{id}a.pdcljan.nc",
    "{id}/climate/{id}a.pdclfeb.nc",
    "{id}/climate/{id}a.pdclmar.nc",
    "{id}/climate/{id}a.pdclapr.nc",
    "{id}/climate/{id}a.pdclmay.nc",
    "{id}/climate/{id}a.pdcljun.nc",
    "{id}/climate/{id}a.pdcljul.nc",
    "{id}/climate/{id}a.pdclaug.nc",
    "{id}/climate/{id}a.pdclsep.nc",
    "{id}/climate/{id}a.pdcloct.nc",
    "{id}/climate/{id}a.pdclnov.nc",
    "{id}/climate/{id}a.pdcldec.nc",
]
variable = "temp_mm_1_5m"


[pr]
preprocessing = "BRIDGE"
processing = "BRIDGE"
[[pr.variables]]
files=[
    "{id}/climate/{id}a.pdcljan.nc",
    "{id}/climate/{id}a.pdclfeb.nc",
    "{id}/climate/{id}a.pdclmar.nc",
    "{id}/climate/{id}a.pdclapr.nc",
    "{id}/climate/{id}a.pdclmay.nc",
    "{id}/climate/{id}a.pdcljun.nc",
    "{id}/climate/{id}a.pdcljul.nc",
    "{id}/climate/{id}a.pdclaug.nc",
    "{id}/climate/{id}a.pdclsep.nc",
    "{id}/climate/{id}a.pdcloct.nc",
    "{id}/climate/{id}a.pdclnov.nc",
    "{id}/climate/{id}a.pdcldec.nc",
]
variable = "precip_mm_srf"

[winds]
preprocessing = "BRIDGE"
processing = "BRIDGE"
[[winds.variables]]
files=[
    "{id}/climate/{id}a.pccljan.nc",
    "{id}/climate/{id}a.pcclfeb.nc",
    "{id}/climate/{id}a.pcclmar.nc",
    "{id}/climate/{id}a.pcclapr.nc",
    "{id}/climate/{id}a.pcclmay.nc",
    "{id}/climate/{id}a.pccljun.nc",
    "{id}/climate/{id}a.pccljul.nc",
    "{id}/climate/{id}a.pcclaug.nc",
    "{id}/climate/{id}a.pcclsep.nc",
    "{id}/climate/{id}a.pccloct.nc",
    "{id}/climate/{id}a.pcclnov.nc",
    "{id}/climate/{id}a.pccldec.nc",
]
variable = "u_mm_p"
[[winds.variables]]
files=[
    "{id}/climate/{id}a.pccljan.nc",
    "{id}/climate/{id}a.pcclfeb.nc",
    "{id}/climate/{id}a.pcclmar.nc",
    "{id}/climate/{id}a.pcclapr.nc",
    "{id}/climate/{id}a.pcclmay.nc",
    "{id}/climate/{id}a.pccljun.nc",
    "{id}/climate/{id}a.pccljul.nc",
    "{id}/climate/{id}a.pcclaug.nc",
    "{id}/climate/{id}a.pcclsep.nc",
    "{id}/climate/{id}a.pccloct.nc",
    "{id}/climate/{id}a.pcclnov.nc",
    "{id}/climate/{id}a.pccldec.nc",
]
variable = "v_mm_p"

[snc]
preprocessing = "BRIDGE"
processing = "BRIDGE"
[[snc.variables]]
files=[
    "{id}/climate/{id}a.ptcljan.nc",
    "{id}/climate/{id}a.ptclfeb.nc",
    "{id}/climate/{id}a.ptclmar.nc",
    "{id}/climate/{id}a.ptclapr.nc",
    "{id}/climate/{id}a.ptclmay.nc",
    "{id}/climate/{id}a.ptcljun.nc",
    "{id}/climate/{id}a.ptcljul.nc",
    "{id}/climate/{id}a.ptclaug.nc",
    "{id}/climate/{id}a.ptclsep.nc",
    "{id}/climate/{id}a.ptcloct.nc",
    "{id}/climate/{id}a.ptclnov.nc",
    "{id}/climate/{id}a.ptcldec.nc",
]
variable = "snowCover_mm_srf"


[liconc]
preprocessing = "BRIDGE"
processing = "BRIDGE"
[[liconc.variables]]
files=[
    "{id}/climate/{id}a.ptcljan.nc",
    "{id}/climate/{id}a.ptclfeb.nc",
    "{id}/climate/{id}a.ptclmar.nc",
    "{id}/climate/{id}a.ptclapr.nc",
    "{id}/climate/{id}a.ptclmay.nc",
    "{id}/climate/{id}a.ptcljun.nc",
    "{id}/climate/{id}a.ptcljul.nc",
    "{id}/climate/{id}a.ptclaug.nc",
    "{id}/climate/{id}a.ptclsep.nc",
    "{id}/climate/{id}a.ptcloct.nc",
    "{id}/climate/{id}a.ptclnov.nc",
    "{id}/climate/{id}a.ptcldec.nc",
]
variable = "fracPFTs_mm_srf"

[pfts]
preprocessing = "BRIDGE"
processing = "BRIDGE"
[[pfts.variables]]
files=[
    "{id}/climate/{id}a.ptcljan.nc",
    "{id}/climate/{id}a.ptclfeb.nc",
    "{id}/climate/{id}a.ptclmar.nc",
    "{id}/climate/{id}a.ptclapr.nc",
    "{id}/climate/{id}a.ptclmay.nc",
    "{id}/climate/{id}a.ptcljun.nc",
    "{id}/climate/{id}a.ptcljul.nc",
    "{id}/climate/{id}a.ptclaug.nc",
    "{id}/climate/{id}a.ptclsep.nc",
    "{id}/climate/{id}a.ptcloct.nc",
    "{id}/climate/{id}a.ptclnov.nc",
    "{id}/climate/{id}a.ptcldec.nc",
]
variable = "fracPFTs_mm_srf"

[tos]
preprocessing = "BRIDGE"
processing = "BRIDGE"
[[tos.variables]]
files=[
    "{id}/climate/{id}o.pfcljan.nc",
    "{id}/climate/{id}o.pfclfeb.nc",
    "{id}/climate/{id}o.pfclmar.nc",
    "{id}/climate/{id}o.pfclapr.nc",
    "{id}/climate/{id}o.pfclmay.nc",
    "{id}/climate/{id}o.pfcljun.nc",
    "{id}/climate/{id}o.pfcljul.nc",
    "{id}/climate/{id}o.pfclaug.nc",
    "{id}/climate/{id}o.pfclsep.nc",
    "{id}/climate/{id}o.pfcloct.nc",
    "{id}/climate/{id}o.pfclnov.nc",
    "{id}/climate/{id}o.pfcldec.nc",
]
variable = "temp_mm_uo"
[[tos.variables]]
files="{id}/inidata/{id}.qrparm.omask.nc"
variable = "lsm"

[mlotst]
preprocessing = "BRIDGE"
processing = "BRIDGE"
[[mlotst.variables]]
files=[
    "{id}/climate/{id}o.pfcljan.nc",
    "{id}/climate/{id}o.pfclfeb.nc",
    "{id}/climate/{id}o.pfclmar.nc",
    "{id}/climate/{id}o.pfclapr.nc",
    "{id}/climate/{id}o.pfclmay.nc",
    "{id}/climate/{id}o.pfcljun.nc",
    "{id}/climate/{id}o.pfcljul.nc",
    "{id}/climate/{id}o.pfclaug.nc",
    "{id}/climate/{id}o.pfclsep.nc",
    "{id}/climate/{id}o.pfcloct.nc",
    "{id}/climate/{id}o.pfclnov.nc",
    "{id}/climate/{id}o.pfcldec.nc",
]
variable = "mixLyrDpth_mm_uo"
[siconc]
preprocessing = "BRIDGE"
processing = "BRIDGE"
[[siconc.variables]]
files=[
    "{id}/climate/{id}o.pfcljan.nc",
    "{id}/climate/{id}o.pfclfeb.nc",
    "{id}/climate/{id}o.pfclmar.nc",
    "{id}/climate/{id}o.pfclapr.nc",
    "{id}/climate/{id}o.pfclmay.nc",
    "{id}/climate/{id}o.pfcljun.nc",
    "{id}/climate/{id}o.pfcljul.nc",
    "{id}/climate/{id}o.pfclaug.nc",
    "{id}/climate/{id}o.pfclsep.nc",
    "{id}/climate/{id}o.pfcloct.nc",
    "{id}/climate/{id}o.pfclnov.nc",
    "{id}/climate/{id}o.pfcldec.nc",
]
variable = "iceconc_mm_uo"
[[siconc.variables]]
files="{id}/inidata/{id}.qrparm.omask.nc"
variable = "lsm"


[oceanCurrents]
preprocessing = "BRIDGE"
processing = "BRIDGE"
[[oceanCurrents.variables]]
files="{id}/climate/{id}o.pgclann.nc"
variable = "ucurrTot_ym_dpth"
[[oceanCurrents.variables]]
files="{id}/climate/{id}o.pgclann.nc"
variable = "vcurrTot_ym_dpth"

[height]
preprocessing = "BRIDGE"
processing = "BRIDGE"
[[height.variables]]
files="{id}/inidata/{id}.qrparm.orog.nc"
variable = "ht"
[[height.variables]]
files="{id}/inidata/{id}.qrparm.omask.nc"
variable = "depthdepth"