[Model]
dir = "climatearchive_sample_data/data"
name = "Bridge"
[Model.Atmosphere]
levels = [1000, 850, 700, 500, 200, 100, 10]
unit = "hPa"
[Model.Ocean]
levels = [0, 100, 200, 500, 1000, 2000, 4000]
unit = "m"

[clt]
preprocessing = "BRIDGE"
processing = "BRIDGE"
[[clt.variables]]
files=["{id}/climate/{id}a.pdclann.nc"]
variable = "totCloud_mm_ua"

[tas]
preprocessing = "BRIDGE"
processing = "BRIDGE"
[[tas.variables]]
files=["{id}/climate/{id}a.pdclann.nc"]
variable = "temp_mm_1_5m"

[pr]
preprocessing = "BRIDGE"
processing = "BRIDGE"
[[pr.variables]]
files=["{id}/climate/{id}a.pdclann.nc"]
variable = "precip_mm_srf"

[winds]
preprocessing = "BRIDGE"
processing = "BRIDGE"
[[winds.variables]]
files=["{id}/climate/{id}a.pcclann.nc"]
variable = "u_mm_p"
[[winds.variables]]
files=["{id}/climate/{id}a.pcclann.nc"]
variable = "v_mm_p"

[height]
preprocessing = "BRIDGE"
processing = "BRIDGE"
[[height.variables]]
files="{id}/inidata/{id}.qrparm.orog.nc"
variable = "ht"