[Model]
dir = "/home/bridge/wb19586/umdata"
name = "Bridge"
[Model.Atmosphere]
levels = [1000, 850, 700, 500, 200, 100, 10]
unit = "hPa"
[Model.Ocean]
levels = [0, 100, 200, 500, 1000, 2000, 4000]
unit = "m"

[tas]
preprocessing = "BRIDGE"
processing = "BRIDGE"
[[tas.variables]]
files="{regex}{id}/pj/{id}a#pj000000004(jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)+.nc"
# files=["{id}/pj/{id}a#pj000000004mar+.nc"]
variable = "temp_1_5m"


[pr]
preprocessing = "BRIDGE"
processing = "BRIDGE"
[[pr.variables]]
# files="{regex}{id}/pj/{id}a#pj000000004(jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)+.nc"
files=["{id}/pj/{id}a#pj000000004mar+.nc"]
variable = "precip_6hr_srf"


# [height]
# preprocessing = "BRIDGE"
# processing = "BRIDGE"
# [[height.variables]]
# files="{id}/inidata/{id}.qrparm.orog.nc"
# variable = "ht"
# [[height.variables]]
# files="{id}/inidata/{id}.qrparm.omask.nc"
# variable = "depthdepth"