[[variables]]
output_variable = "clt"
realm = "a"
output_stream = "pd"
named_input_variable = "totCloud_mm_ua"

[[variables]]
output_variable = "tas"
realm = "a"
output_stream = "pd"
named_input_variable = "temp_mm_1_5m"

[[variables]]
output_variable = "pr"
realm = "a"
output_stream = "pd"
named_input_variable = "precip_mm_srf"

[[variables]]
output_variable = "winds"
realm = "a"
output_stream = "pc"
named_input_variable = "u_mm_p"

[[variables]]
output_variable = "snc"
realm = "a"
output_stream = "pt"
named_input_variable = "snowCover_mm_srf"

[[variables]]
output_variable = "liconc"
realm = "a"
output_stream = "pt"
named_input_variable = "fracPFTs_mm_srf"

[[variables]]
output_variable = "pfts"
realm = "a"
output_stream = "pt"
named_input_variable = "fracPFTs_mm_srf"

[[variables]]
output_variable = "tos"
realm = "o"
output_stream = "pf"
named_input_variable = "temp_mm_uo"

[[variables]]
output_variable = "mlotst"
realm = "o"
output_stream = "pf"
named_input_variable = "mixLyrDpth_mm_uo"

[[variables]]
output_variable = "siconc"
realm = "o"
output_stream = "pf"
named_input_variable = "iceconc_mm_uo"

[[variables]]
output_variable = "oceanCurrents"
realm = "o"
output_stream = "pg"
named_input_variable = "ucurrTot_ym_dpth"

[[variables]]
output_variable = "height"
inidata = ""
named_input_variable = "ucurrTot_ym_dpth"