[clt]
realm = "a"
output_stream = "pd"
named_input_variable = "totCloud_mm_ua"

[tas]
realm = "a"
output_stream = "pd"
named_input_variable = "temp_mm_1_5m"

[pr]
realm = "a"
output_stream = "pd"
named_input_variable = "precip_mm_srf"

[winds]
realm = "a"
output_stream = "pc"
named_input_variable = "u_mm_p"

[snc]
realm = "a"
output_stream = "pt"
named_input_variable = "snowCover_mm_srf"

[liconc]
realm = "a"
output_stream = "pt"
named_input_variable = "fracPFTs_mm_srf"

[pfts]
realm = "a"
output_stream = "pt"
named_input_variable = "fracPFTs_mm_srf"

[tos]
realm = "o"
output_stream = "pf"
named_input_variable = "temp_mm_uo"

[mlotst]
realm = "o"
output_stream = "pf"
named_input_variable = "mixLyrDpth_mm_uo"

[siconc]
realm = "o"
output_stream = "pf"
named_input_variable = "iceconc_mm_uo"

[oceanCurrents]
realm = "o"
output_stream = "pg"
named_input_variable = "ucurrTot_ym_dpth"

[height]
inidata = "qrparm.orog"
named_input_variable = "ucurrTot_ym_dpth"